### ISSUE TITLE
Maybe add compatibility for VanillaTweak's Short Sword texture?

### ISSUE THREAD

**Issue by Scarlaid** [betterclient/betterparry#1]
Or maybe somehow make the mod compatible for custom sword?

**Comment by betterclient** [comment]
I think it already does
ill check soon

**Comment by betterclient** [comment]
Hello! I have checked, and the issue seems to be invalid, thanks for reporting anyway!

**Comment by Scarlaid** [comment]
It isn't, in first person view, only in third person. 
Short Swords (Vanilla Tweaks): https://streamable.com/g7avwt
Long Sword (Vanilla): https://streamable.com/nskep5

The version from [here](https://github.com/betterclient/betterparry/releases/tag/1.19.2-1.6) crashed the game also
This is my log: [2023-01-04-1.log](https://github.com/betterclient/betterparry/files/10341706/2023-01-04-1.log)
